name: CI-CD
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch: 
env:
  AZURE_WEBAPP_NAME: rxjsangularmaterial
  NODE_VERSION: '18.x'
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código do repositório
      uses: actions/checkout@v3.6.0
    - name: Setup ambiente Node.js
      uses: actions/setup-node@v3.8.1
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./ProjectSchool/package-lock.json
    - name: Execução do npm install e o teste
      run: |
        npm install
      working-directory: ./ProjectSchool

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Construção da imagem do container da aplicação
      uses: docker/build-push-action@v4.1.1
      with: 
        context: ./ProjectSchool
        file: ./ProjectSchool/Dockerfile
        push: true
        tags: |
          nailtonmagalhaes/RxJS_Angular_Material:latest
          nailtonmagalhaes/RxJS_Angular_Material:v${{ github.run_number }}
          
